version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - VARIANT=${VARIANT:-buster}
    env_file:
      - ../.env
    volumes:
      - ..:/workspace:cached
      - ~/.aws:/root/.aws:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    network_mode: service:db
  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: checkparam
  pma:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD:
      MEMORY_LIMIT: 512M
      UPLOAD_LIMIT: 128M
volumes:
  db-data:
